export const reactQuality = [
  "Frontend Development ",
  "Single Page Applications (SPAs)",
  "Custom Component Development ",
  "API Integration",
  "Migration to ReactJS",
  "Enterprise App Development",
  "UI/UX Enhancement ",
  "Maintenance and Support",
];
export const nodeQuality = [
  "Node.js Consulting And System Architecture Design",
  "Custom Node.js Development",
  "Real-Time Application Development",
  "Serverless Node.js Microservice",
  "API Integration And Development",
  "Node.js Migration And Upgradation",
  "UI/UX Enhancement ",
  "Support And Maintenance",
];
export const fullStackQuality = [
  "Web Application Development",
  "Custom Software Solutions",
  "E-commerce Platforms",
  "Content Management Systems (CMS)",
  "API Development And Integration",
  "Frontend And Backend Development",
  "User Experience (UX) Design",
  "Quality Assurance And Testing",
];
export const phpQuality = [
  "PHP Website Development",
  "Custom Module Development",
  "Third-Party Integration",
  "PHP Framework Development",
  "PHP-Based CMS Development",
  "Full-Stack Development",
  "Custom ERP, CRM & Portal Development",
  "Maintenance & Support",
  "Additional Support",
];
export const laravelQuality = [
  "Laravel Web Development",
  "Laravel Extension Development",
  "API Integration",
  "Full-Stack Development",
  "CMS Solutions",
  "E-commerce Development",
  "Real-Time Interactive Applications",
  "Migration And Upgradation",
  "Maintenance And Support",
];
export const pythonQuality = [
  "Enterprise Python Development",
  "Custom Python Development",
  "API Integration",
  "Web Development",
  "ERP & CRM Development",
  "Machine Learning",
  "Migration And Upgradation",
  "Internet Of Things With Python",
  "Dedicated Python Development",
  "Support & Maintenance",
];
export const wordPressQuality = [
  "Engaging WordPress Design",
  "Custom WordPress Development",
  "Theme Development & Customization",
  "WordPress Plugin & Extension Development",
  "Custom APIs & Integration",
  "SEO-Focused WordPress Solutions",
  "WordPress Migration",
];
export const shopifyQuality = [
  "Shopify Store Development",
  "UI/UX Solution",
  "Shopify Migration Solution",
  "Theme Development And Customization",
  "App Development",
  "Shopify Integration Solution",
  "Shopify Marketing",
  "Support And Maintenance",
  "Shopify Plus Enterprise Services",
];
export const dotNetQuality = [
  ".NET Web And Mobile Application Development",
  ".NET Customization Service",
  "Custom .NET Application Development",
  "ASP.NET Development",
  ".NET API Development",
  ".NET Migration Service",
  "Database Management And Integration",
  "Maintenance And Support Service",
];
export const uiDevQuality = [
  ".User Interface (UI) Design",
  "User Experience (UX) Design",
  "Wireframing And Prototyping",
  "Front-End Development",
  "Responsive Web Development",
  "Cross-Browser Compatibility",
  "PSD-to-HTML Conversion",
  "Mobile App UI/UX",
  "Usability Testing",
  "Accessibility Compliance",
];
export const angularQuality = [
  "Angular Test-Driven Development",
  "Angular Support And Maintenance",
  "UI/UX Solutions",
  "Angular Migration And Upgradation",
  "Angular SPA And Angular Universa",
  "Ecommerce Solutions",
  "Angular Web And Mobile App Development",
  "Angular Consulting Services",
  "Plugin Development",
];
export const nativeQuality = [
  "React Native App Development",
  "Custom Mobile App Solutions",
  "UI/UX Design And Optimization",
  "App Maintenance And Support",
  "Cross-Platform Compatibility",
  "Prototyping And Testing",
  "Performance Optimization",
  "Third-Party Integration",
  "Migration To React Native",
  "Consultation And Strategy",
];
export const javaQuality = [
  "Java-Based Enterprise Applications",
  "Java Product Development",
  "Spring Microservices Development",
  "Spring Core, MVC, And Web Service Development",
  "Spring Security, Kafka, And JPA Development",
  "Legacy Application Migration",
  "Maintenance And Support",
  "Big Data And Analytics With Java",
  "IoT With Java",
];
export const androidQuality = [
  "Consultation And Strategy",
  "Custom Android App Development",
  "UI/UX Design",
  "Cross-Platform Development",
  "App Migration And Upgrades",
  "Third-Party Integrations",
  "Quality Assurance",
  "App Store Deployment",
  "Maintenance And Support",
];
export const swiftQuality = [
  "Custom iOS App Development",
  "iOS App Development",
  "App Enhancement And Updates",
  "Cross-Platform Development",
  "Swift Migration And Porting",
  "UI/UX Design And Optimization",
  "Performance Enhancement",
  "API Integration",
  "App Maintenance And Support",
  "Consultation And Strategy",
];
