import Black1 from "../../../assets/images/SeoExpert/Tab-icon-black1.png";
import White1 from "../../../assets/images/SeoExpert/Tab-icon-white1.png";
import Black2 from "../../../assets/images/SeoExpert/Tab-icon-black2.png";
import White2 from "../../../assets/images/SeoExpert/Tab-icon-white2.png";
import Black3 from "../../../assets/images/SeoExpert/Tab-icon-black3.png";
import White3 from "../../../assets/images/SeoExpert/Tab-icon-white3.png";
import Black4 from "../../../assets/images/SeoExpert/Tab-icon-black4.png";
import White4 from "../../../assets/images/SeoExpert/Tab-icon-white4.png";
import Black5 from "../../../assets/images/SeoExpert/Tab-icon-black5.png";
import White5 from "../../../assets/images/SeoExpert/Tab-icon-white5.png";
import Black6 from "../../../assets/images/SeoExpert/Tab-icon-black6.png";
import White6 from "../../../assets/images/SeoExpert/Tab-icon-white6.png";
import Black7 from "../../../assets/images/SeoExpert/Tab-icon-black7.png";
import White7 from "../../../assets/images/SeoExpert/Tab-icon-white7.png";
export const tabdata = [
  {
    id: 1,
    iconBlack: Black1,
    iconWhite: White1,
    name: "Site Audit (Onsite Technical SEO)",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Mapping Keyword topics",
      "Xml Sitemap/Analysis",
      "Canonicals",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Google Analytics Set Up (If Not Setup)",
      "Redirection analysis",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Website Load Time & Speed Test",
      "Image & Hyperlink Optimization      ",
      "Alt Text",
      "Bing Webmaster Tools Set Up (If Not Set Up)",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 2,
    iconBlack: Black2,
    iconWhite: White2,
    name: "Keyword/Competitor Analysis",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Mapping Keyword topics",
      "Xml Sitemap/Analysis",
      "Canonicals",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Redirection analysis",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Image & Hyperlink Optimization      ",
      "Alt Text",
      "Bing Webmaster Tools Set Up (If Not Set Up)",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 3,
    iconBlack: Black3,
    iconWhite: White3,
    name: "Keywords/pages Optimization",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Mapping Keyword topics",
      "Canonicals",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Redirection analysis",
      "Google Analytics Set Up (If Not Setup)",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Website Load Time & Speed Test",
      "Image & Hyperlink Optimization      ",
      "Bing Webmaster Tools Set Up (If Not Set Up)",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 4,
    iconBlack: Black4,
    iconWhite: White4,
    name: "Onsite Content",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Mapping Keyword topics",
      "Xml Sitemap/Analysis",
      "Canonicals",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Redirection analysis",
      "Google Analytics Set Up (If Not Setup)",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Website Load Time & Speed Test",
      "Image & Hyperlink Optimization      ",
      "Alt Text",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 5,
    iconBlack: Black5,
    iconWhite: White5,
    name: "Backlink building ( External Back Linking)",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Xml Sitemap/Analysis",
      "Canonicals",
      "Redirection analysis",
      "Google Analytics Set Up (If Not Setup)",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Website Load Time & Speed Test",
      "Image & Hyperlink Optimization      ",
      "Alt Text",
      "Bing Webmaster Tools Set Up (If Not Set Up)",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 6,
    iconBlack: Black6,
    iconWhite: White6,
    name: "Local SEO",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Mapping Keyword topics",
      "Xml Sitemap/Analysis",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Redirection analysis",
      "Google Analytics Set Up (If Not Setup)",
      "Meta descriptions",
      "SEO Friendly Urls Suggestions",
      "Website Load Time & Speed Test",
      "Alt Text",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
  {
    id: 7,
    iconBlack: Black7,
    iconWhite: White7,
    name: "Reporting",
    text: [
      "Header Tags Optimization",
      "Website Taxonomy Analysis",
      "Robots.Txt Analysis",
      "Mapping Keyword topics",
      "Xml Sitemap/Analysis",
      "Google Webmaster Tools Set Up (If Not Set Up)",
      "Redirection analysis",
      "Meta descriptions",
      "Website Load Time & Speed Test",
      "Image & Hyperlink Optimization      ",
      "Bing Webmaster Tools Set Up (If Not Set Up)",
      "Titles",
      "Broken Link Analysis & Fixing",
    ],
  },
];
