export const option = [
  { value: "SEO", label: "SEO" },
  { value: "SEM", label: "SEM" },
  { value: "SMM", label: "SMM" },
  { value: "SMO", label: "SMO" },
  { value: "Web App Dev", label: "Web App Dev" },
  { value: "UI/UX Designing", label: "UI/UX Designing" },
  { value: "UI/UX Development", label: "UI/UX Development" },
  { value: "Devops", label: "Devops" },
  { value: "Graphic Designing", label: "Graphic Designing" },
  { value: "Ecommerce", label: "Ecommerce" },
  { value: "Wordpress Development", label: "Wordpress Development" },
  { value: "Android Development", label: "Android Development" },
  { value: "IOS Development", label: "IOS Development" },
  { value: "React Native Dev", label: "React Native" },
  { value: "Flutter Development", label: "Flutter Development" },
  { value: "AI Development", label: "AI Development" },
  { value: "Email Marketing", label: "Email Marketing" },
  { value: "Content Marketing", label: "Content Marketing" },
  { value: "Youtube Marketing", label: "Youtube Marketing" },
  { value: "AI Website Audit", label: "AI Website Audit" },
  { value: "AI Compititor Analysis", label: "AI Compititor Analysis" },
  { value: "Email Chat Support", label: "Email Chat Support" },
  { value: "Inbound Calls", label: "Inbound Calls" },
  { value: "Outbound Calls", label: "Outbound Calls" },
  { value: "Cold Calling", label: "Cold Calling" },
];
