export const processData = [
  {
    id: 1,
    heading: "Analysis of Requirements",
    list1: "Get to know our client",
    list2: "Comprehending client’s requirement",
    list3: "Proposing a solution",
    addBefore: true,
    addMobileBefore: true,
  },
  {
    id: 2,
    heading: "App Development Strategies",
    list1: "Make business strategies",
    list2: "Frame strategies based on needs",
    list3: "Get your feedback",
    addBefore: true,
  },
  {
    id: 3,
    heading: "Wireframing & Designing",
    list1: "Blueprint structure",
    list2: "Wireframing each screen",
    list3: "Designing the app ",
    addBefore: true,
  },
  {
    id: 4,
    heading: "Development",
    list1: "Coding the app",
    list2: "Layout main sections",
    list3: "Client’s feedback",
    addBefore: false,
  },
  {
    id: 5,
    heading: "Testing",
    list1: "Testing the ap",
    list2: "100% bug-free",
    list3: "Get final approval from the client ",
    addBefore: false,
  },
  {
    id: 6,
    heading: "Deployment",
    list1: "Deploy to App Stores",
    list2: "Deploy to client’s server",
    list3: "App available for users",
    addBefore: false,
  },
];
