export const option = [
  { value: "Node Js Developer", label: "Node Js Developer" },
  { value: ".Node Js Developer", label: ".Net Developer" },
  { value: "React Js Developer", label: "React Js Developer" },
  { value: "Seo Expert", label: "Seo Expert" },
  { value: "Socia Media Expert", label: "Socia Media Expert" },
  { value: "PPC Expert", label: "PPC Expert" },
  { value: "Content Writer", label: "Content Writer" },
  { value: "Email Expert", label: "Email Expert" },
  { value: "Full Stack Developer", label: "Full Stack Developer" },
  { value: "Laravel Developer", label: "Laravel Developer" },
  { value: "Python Developer", label: "Python Developer" },
  { value: "UI/UX Developer", label: "UI/UX Developer" },
  { value: "UI/UX Designer", label: "UI/UX Designer" },
  { value: "Graphic Designer", label: "Graphic Designer" },
  { value: "Angular Developer", label: "Angular Developer" },
  { value: "React Native Developer", label: "React Native Developer" },
  { value: "Java Developer", label: "Java Developer" },
  { value: "Android Developer", label: "Android Developer" },
  { value: "swift Developer", label: "swift Developer" },
  { value: "SQA Engineer", label: "SQA Engineer" },
  { value: "Penetration Tester", label: "Penetration Tester" },
  { value: "Project Cordinator", label: "Project Cordinator" },
  { value: "Project Manager", label: "Project Manager" },
  {
    value: "Automation Engineer",
    label: "Automation Engineer",
    color: "purple",
  },
];
